// Test_Material_Class.idl : IDL source for Test_Material_Class
//

// This file will be processed by the MIDL tool to
// produce the type library (Test_Material_Class.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(13DE0C3A-0CF7-42AF-8634-41879FADFFEE),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICapeMaterialObject : IDispatch{
};
[
	object,
	uuid(F61A9DA7-98F6-47C2-8749-3013C7490373),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface Ixx : IDispatch{
};
[
	uuid(700CC474-6E89-4EBB-A82A-48F930DA7918),
	version(1.0),
]
library Test_Material_ClassLib
{
	importlib("stdole2.tlb");
	[
		uuid(E28C0506-E0BA-4D5C-973A-812141857D46)		
	]
	coclass CapeMaterialObject
	{
		[default] interface ICapeMaterialObject;
	};
	[
		uuid(96BDEA21-36C7-4323-B361-5682A345B202)		
	]
	coclass xx
	{
		[default] interface Ixx;
	};
};

