#ifndef __EditWndinfo_Dialog__
#define __EditWndinfo_Dialog__

/**
@file
Subclass of info_Dialog, which is generated by wxFormBuilder.
*/

#include "auto_CEditWnd.h"

//// end generated include

/** Implementing info_Dialog */
class EditWndinfo_Dialog : public info_Dialog
{
	public:
		/** Constructor */
		EditWndinfo_Dialog( wxWindow* parent );
	//// end generated class members
	
};

#endif // __EditWndinfo_Dialog__
