// A2F.idl : IDL source for A2F
//

// This file will be processed by the MIDL tool to
// produce the type library (A2F.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F6EB158D-ECFB-4FCC-804A-B5DA52D4450F),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IUnitOperations : IDispatch{
};
[
	object,
	uuid(373AF87E-7579-43F8-B97D-045DCCE88E9E),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPortCollection : IDispatch{
};
[
	object,
	uuid(EBBFAD37-B5F7-489E-87E2-C0DAA10D6D79),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IUnitPort : IDispatch{
};
[
	uuid(E304CE16-F539-4DCA-BEF1-A77F6C1E447F),
	version(1.0),
]
library A2FLib
{
	importlib("stdole2.tlb");
	[
		uuid(A9129436-FB2C-4D26-B88D-A61E4D594BCB)		
	]
	coclass UnitOperations
	{
		[default] interface IUnitOperations;
	};
	[
		uuid(B837F485-6A5A-4B3C-A6CA-2D5A0440060F)		
	]
	coclass PortCollection
	{
		[default] interface IPortCollection;
	};
	[
		uuid(323340E4-D19F-44F4-AF0E-A051D407FC45)		
	]
	coclass UnitPort
	{
		[default] interface IUnitPort;
	};
};

